### ISSUE TITLE
Updating Sublime breaks Mavensmate

### ISSUE THREAD

**Issue by njjc** [joeferraro/MavensMate-app#125]
Updating Sublime Text to "Stable Channel, Build 3114" causes mavensmate to throw exceptions, breaks functionality.

Are there any plans to for future releases, or is this officially abandoned?

**Comment by joeferraro** [comment]
Hi @njjc, can you please update your issue according to our guidelines? thanks!

https://github.com/joeferraro/MavensMate-app/blob/master/CONTRIBUTING.md

**Comment by njjc** [comment]
1. OS X 10.11.4 
2. MavensMate v0.0.10
3. N/A
4. Update sublime to the latest stable release, build 3114. Close and reopen Sublime.
5. No log was created despite the appropriate settings being placed, here are the errors received: 
![screen shot 2016-05-17 at 9 25 24 am](https://cloud.githubusercontent.com/assets/1018198/15330365/6d522ca4-1c11-11e6-9e4a-51d3d29bc72a.png)
Afterwords, saving files still works, but cmd+shift+r to quick open doesn't work, and syntax highlighting is broken.

**Comment by joeferraro** [comment]
Technically, this is a text editor issue and one that has been resolved in the Sublime Text project. https://github.com/joeferraro/MavensMate-SublimeText/issues/784

v7 and v6 have both been patched:

https://github.com/joeferraro/MavensMate-SublimeText/releases/tag/v7.0.0-beta.2
https://github.com/joeferraro/MavensMate-SublimeText/releases/tag/v6.0.3

**Comment by njjc** [comment]
Updating fixed it! Thanks Joe, I love Mavensmate! Keep up the great work.

**Comment by mikepaisner** [comment]
Joe,
Can you comment on the state/plans for V6 and V7?  Just wondering if they will continue to live in parallel or will they be joined at some point.

Still a huge fan of MavensMate!

Mike

**Comment by njjc** [comment]
Another error after updating:
<img width="532" alt="screen shot 2016-05-17 at 9 34 35 am" src="https://cloud.githubusercontent.com/assets/1018198/15330646/9dac20ca-1c12-11e6-859f-82c08ec4e323.png">
