### ISSUE TITLE
Error: Could not create Trace Flags: LogType is required.: LogType

### ISSUE THREAD

**Issue by OlegForce** [joeferraro/MavensMate-app#126]
Sorry if this is a dupe. Keep getting this error when trying to use Execute code. The MM app pops up, but it has this error in the message - Error: Could not create Trace Flags: LogType is required.: LogType

**Comment by kbespalyi** [comment]
Put additional parameters to /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/sfdc-client.js started from line 919:

                LogType: debugLevels.LogType || 'USER_DEBUG',
                DebugLevelId: debugLevels.DebugLevelId || 'SFDC_DevConsole'

and also to your project:
to config/.debug file to "levels" key

        "LogType": "USER_DEBUG",
        "DebugLevelId": "xxxxxxxxxxxx"

DebugLevelId you can find from SalesForce Debug Level Details just copy last part of url.

**Comment by OlegForce** [comment]
That did not work and also doesnt seem to be a good repeatable way of doing that :) I have 25 projects in my sublime :)

**Comment by donaldrivard** [comment]
Has this been resolved? I am getting the same error. I have set me version to 34.0 but still the same error. And the above workaround does not work for me also.

**Comment by sebastiankessel** [comment]
Same here.... Not only the fix above doesn't work for me, but I can't seem to download the correct package that contains the fixes @joeferraro merged on 6/27

**Comment by kbespalyi** [comment]
I just stop to use MavenMate, and moved to IntelliJ IDEA InteliCloud plugin to be more productive :)

**Comment by abhidotnet** [comment]
I am facing this issue on Windows 10 64 bit. I am unable to find the **/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/sfdc-client.js**
I looked into %APPDATA% folders as well as %PROGRAMFILES% folders.

**Comment by abhidotnet** [comment]
I was able to discover this file by running the good old dos command 
**`dir /s sfdc-client.js`**
