### ISSUE TITLE
Can't open MavensMate 0.0.11 beta1 and beta2

### ISSUE THREAD

**Issue by jeancdc** [joeferraro/MavensMate-app#129]
I've got this message when I open the MavensMate app 0.0.11 beta1 (translated from french):
`"MavensMate" is damaged and can not be opened. You should place the item in the trash.`

And when I want open the 0.0.11 beta2 version:
`Can not open the application "MavensMate".`

When I checked the log in the console:
```com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x10000020.Electron[3729]) Could not find and/or execute program specified by service: 2: No such file or directory: /Applications/MavensMate.app/Contents/MacOS/Electron```

The 0.0.11 beta1 version was working before I tried to install the beta2 version.

I'm using Mac OSX 10.11.5

**Comment by joeferraro** [comment]
Yeah these are pre-releases, I would not recommend installing them
