### ISSUE TITLE
Blank Mavensmate App

### ISSUE THREAD

**Issue by westhechiang** [joeferraro/MavensMate-app#140]
Is anyone else experiencing a blank Mavensmate app:
![image](https://cloud.githubusercontent.com/assets/7388796/17184703/83d5978c-53e2-11e6-828f-25c885b7561b.png)

I LOVE what you have created joe and the thought of having to use the Force.com IDE makes me want to stop Salesforce development permanently. 100% respect your decision to spend more time with your newborn daughter (congrats btw!) but I'm sure I speak for the rest of the community that  we hope you resume development soon!

**Comment by westhechiang** [comment]
FYI, I'm on the latest Mavensmate-app version as well as the latest sublime text mavensmate plugin. I just tried installing the Mavensmate-app on a colleague's computer and it works fine on his.

**Comment by westhechiang** [comment]
Wow. This is fixed. User-error. I had modified my /etc/hosts and accidentally deleted the line: 
`127.0.0.1       localhost`

**Comment by nicklaulu** [comment]
I also encountered the same problem. Can you elaborate on your solution?
Thanks!
