### ISSUE TITLE
Q:  MavensMate for Sublime Text v5.0.0-beta.1 ERROR

### ISSUE THREAD

**Issue by Eaton-Cirrius** [joeferraro/mavensmate-app#2]
Hey Joe,

Not sure if this is the place to post this but I just got the following error when I opened ST3 & MM this morning. I didn't install anything new.  It looks like MM might have updated itself to this beta version?  Is that possible?  I'm a bit lost on how to get back to a stable version (4.0.5).  Any help would be appreciated.

"MavensMate for Sublime Text v5.0.0-beta.1

[ERROR]: Could not contact local MavensMate server, please ensure the MavensMate app is installed and running (https://github.com/joeferraro/mavensmate-app/releases). MavensMate will not run properly until resolved."

Thanks in advance,
Mike

**Comment by joeferraro** [comment]
Hey Mike, see this post: https://github.com/joeferraro/MavensMate/issues/483

**Comment by Eaton-Cirrius** [comment]
Joe,

Thanks so much for the quick response!  Don't know how I missed that issue!

Love MavensMate!

Thanks again,
Mike

On Thu, Aug 13, 2015 at 11:57 AM, Joe Ferraro <notifications@github.com>
wrote:

> Closed #2 <https://github.com/joeferraro/mavensmate-app/issues/2>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joeferraro/mavensmate-app/issues/2#event-381680891>.
>



-- 
*Michael Eaton*
Salesforce.com Solutions Architect
512.782.9941 :office
203.994.2664 :cell
mike.eaton@cirriussolutions.com
www.linkedin.com/in/michaeleeaton
