### ISSUE TITLE
Installing MavensMateApp: add option to change install location.

### ISSUE THREAD

**Issue by coolbulevar** [joeferraro/MavensMate-app#26]
Please add this feature.
Also i found that windows x64 version of app automatically installs in "Program Files (x86)" and there are no option to choose install location.

**Comment by KoenVM** [comment]
+1 for this, or even better make a portable version of it. In a corporate world, unfortunately you don't often have admin rights...

**Comment by coolbulevar** [comment]
Thank you Joe!
