### ISSUE TITLE
INVALID_LOGIN Error

### ISSUE THREAD

**Issue by Wizardum** [joeferraro/MavensMate-app#28]
Hi Joe,

Today I was prompted to install MavensMate-app when I opened my SF sublime project.

However I can't seem to be able to login to any of my SF projects through the app.
I keep getting the same error `INVALID_LOGIN: Invalid username, password, security token; or user locked out.`
But I'm pretty sure my credentials are correct. I tried it with different SF orgs and yesterday I was able to save and compile apex code to SF without any issues.

Looking forward to any insights about this issue as I would love to avoid the SF Developer Console for development.

As a note of appreciation, you have been doing incredible work with the MavensMate plugin. Thanks a lot.

Best regards

**Comment by joeferraro** [comment]
Platform?

**Comment by Wizardum** [comment]
Ahh yes.
I'm working on a Windows 7 x64 machine and I've installed the x64 version of the MavensMate-app.

**Comment by joeferraro** [comment]
Can you create new projects?

**Comment by Wizardum** [comment]
I can't do that either. Same issue.

**Comment by joeferraro** [comment]
Try creating a project with the following creds:

username: mm2@force.com
password: force
org type: developer

**Comment by jlyonas** [comment]
I've encountered similar issues for any projects involving Custom URL org types. The 0.0.6 update allowed me to maintain my credentials so long as the app was open. However closing and opening the app requires re-entry of Custom URL org type before I can open my project. I would question whether this is just Custom URL org types or if the credentials for org type altogether lack persistence.

**Comment by Wizardum** [comment]
I had an issue with the security tokens so I had to reset it and it is working now.
Thanks for you help and apologies for any trouble ;)

**Comment by joeferraro** [comment]
I think @jlyonas may be on to something. investigating this morning, will re-open this issue if i can confirm

**Comment by joeferraro** [comment]
cheers, @Wizardum :+1:

**Comment by jlyonas** [comment]
I opened a separate issue for the Org Type. With Screen Shot.

**Comment by rrcook** [comment]
I am having the same issue, MavensMate app won't take my credentials
Windows 7 x64
MavensMate app v0.0.9 Beta 2
Installed as a portable application
In settings, have turned off "Use keyring"

**Comment by joeferraro** [comment]
Is this during project creation? Is this a sandbox? Are you using a custom URL? Are you appending your security token if needed?

**Comment by rrcook** [comment]
This is not during project creation.
This is a sandbox for my company's org.
I am not using a custom url. I am putting in my login info for the sandbox and picking "sandbox" from the dropdown.
Since it is a sandbox I am not appending a security token.

**Comment by joeferraro** [comment]
Sandboxes do not automatically exempt you from using a security token.

**Comment by mikepaisner** [comment]
I also have had problems getting MavensMate App to open a project.  Sometimes it works, other times I get an Invalid login.  Unfortunately, I can't recreate it at the moment, but it happened a lot yesterday.

Windows 7 x64
Installed MavensMate-App as normal application (not portable)
Currently on v0.0.7-beta4
no modifications to default settings except for mm_workspace
this is connecting to existing sandbox
I did not enter custom url
did not enter security token, just password

**Comment by joeferraro** [comment]
@mikepaisner thanks for the info. if you encounter the issue, would you mind generating logs and pasting them? thanks

**Comment by rrcook** [comment]
My problems have cleared up, I am now able to log in and save/compile Apex classes.
Windows 7 X64, Mavensmate app 0.0.9 portable, using keyring and Sublime Text 3 plugin 5.0.4.
Thanks for your work on this.

**Comment by joeferraro** [comment]
@rrcook you're welcome :+1:

**Comment by ravinder4a2** [comment]
@joeferraro I'm having same issue on creation of new project for sandbox. My user credentials are correct  & running on windows 7. Any help would be appreciated . Thanks for help in advance .
