### ISSUE TITLE
Allow Editor Driven Creation Dialogs

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/mavensmate-app#3]
Using 5.0.0-beta2 if I create a new visualforce page, there is a noticeable lag while waiting for the mavens mate app to load the visualforce creation dialog page. Once there, I'm unable to use the keyboard to select the metadata template and complete the creation.

While I understand that this is intended to address a gap with some editors, i.e. ST 3, to provide more UI friendly interactions with the mavensmate app, and hence improve usability for pages that require complex inputs, there is another camp of developers who don't ever want to have to leave the keyboard who lose out with this change. 

Personally, the major reason I switched to ST3 + MM is that ST3 is super fast from the keyboard, everything has a shortcut, everything can be launched from the command palette, nothing requires a keyboard. In contrast all the app dialogs for eclipse with it's plugin are clunky, slow, and typically don't have keyboard shortcuts. For creating a vf page with the pre-5.0.0 version, I didn't need to leave the keyboard to complete, or wait for related apps to load.

Perhaps there is a way we can have both our cake and eat it too by allowing users to choose whether certain dialogs (such as selecting the page template), or done in the app, or via the editor plugin, so that those who want exclusively keyboard can get it, and those that need a more UI based approach can choose that route ...

**Comment by ralphcallaway** [comment]
to give some context, the app is taking between 5-20s to load after submitting the create vf page command ...

**Comment by joeferraro** [comment]
yeah something's not right then. can you record a screencast?

**Comment by joeferraro** [comment]
it looks like GitHub was experiencing API issues: https://status.github.com/messages

Could this be the problem? I've never seen waits like you describe

**Comment by ralphcallaway** [comment]
@joeferraro yep, seems like that was what was cause the performance issue, it's pretty snappy now ...

leaving this open since it's mainly intended to touch on improving support for keyboard driven workflows

seems like we could architect this in a way that there is a node command line core, and the app itself is just chrome for UI interactions, would open the possibility of skipping the chrome if desired

**Comment by joeferraro** [comment]
fyi, there is a node command line core, the ST plugin simply uses HTTP out of convenience. we could still use the HTTP request, only the request to create new metadata without the UI would have a specific flag that basically says, "create a new piece of metadata using the default template"

**Comment by ralphcallaway** [comment]
@joeferraro gotcha, assuming that command line could also take a text body (say if we added a flag to use the ST3 dropdown for the template selection instead of the app ui)

**Comment by ralphcallaway** [comment]
migrated to https://github.com/joeferraro/MavensMate-SublimeText/issues/631
