### ISSUE TITLE
Open in Sublime Menu Bug

### ISSUE THREAD

**Issue by jlyonas** [joeferraro/MavensMate-app#32]
Open Project in Mavensmate-App, then Open in Sublime causes two instances of Sublime Text to open. 1 for your last instance of Sublime Text and 2 for the project you are opening.

Installed on Windows 7 x64

**Comment by joeferraro** [comment]
I agree, this is annoying, unfortunately, there's not a whole lot we can do here that would be worth the time effort. The sublime text command line tool does not allow us to target specific ST windows.
