### ISSUE TITLE
No Persistence of Org Type Credentials on Windows 7 x64

### ISSUE THREAD

**Issue by jlyonas** [joeferraro/MavensMate-app#33]
Each time I open the app, I need to re-enter org type project credentials. Whether I open the project from the UI or from within Sublime Text.

My username, password/token combo are there, but the Org Type has been reset to Developer. It should be a Custom URL.

Screenshot http://imgur.com/ARFxi8p

Keychain Setting is Off.
Installed on Windows 7 x64

Edit: This appears to only effect my Custom URL Org Type projects. Tested on a Sandbox Org Type with no issue.

**Comment by joeferraro** [comment]
this has been resolved since 0.0.7. closing for now. if you're still experiencing this issue, please don't hesitate to re-open

**Comment by jlyonas** [comment]
Installed 0.0.8 this morning. Working just fine! Great! Thanks!

**Comment by joeferraro** [comment]
cheers @jlyonas
