### ISSUE TITLE
MavensMate load issue

### ISSUE THREAD

**Issue by Inbarajd** [joeferraro/MavensMate-app#36]
I am getting the following error when I open my Sublime Text. 

DPI scale: 1
startup, version: 3083 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/User1/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/User1/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/User1/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.251626
startup time: 0.291626
first paint time: 0.293626
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Alignment.Alignment
reloading plugin Lightning.lightningsave
reloading plugin Lightning.semver
reloading plugin Lightning.walk_up
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
plugins loaded
WE ARE TOTALLY LOADED!
Package Control: Installing 1 missing package
ignored packages updated to: ["MavensMate", "Vintage"]
reloading Packages/User/Package Control.sublime-settings
Package Control: Installed missing package MavensMate
Package Control: Skipping automatic upgrade, last run at 2015-09-30 14:32:32, next run at 2015-09-30 15:32:32 or after
ignored packages updated to: ["Vintage"]
reloading Packages/User/Preferences.sublime-settings
reloading plugin MavensMate.config
reloading plugin MavensMate.mavensmate
[MAVENSMATE]: reloading modules
[MAVENSMATE]: =============> Starting MavensMate for Sublime Text
[MAVENSMATE]: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>
reloading plugin MavensMate.util
generating syntax summary
generating meta info summary
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
[MAVENSMATE]: Calling mavensmate adapter
[MAVENSMATE]: OPERATION: new-project
[MAVENSMATE]: {'body': {'args': {'ui': True}}}
[MAVENSMATE]: http://localhost:56248/execute?command=new-project&async=1&pid=4W6EWHKSY5F7BCBNO5F3K1CN62Q18WJI
[MAVENSMATE]: posting to MavensMate:
[MAVENSMATE]: b'{"args": {"ui": true}}'
[MAVENSMATE]: urllib.error.URLError
[MAVENSMATE]: Error contacting local MavensMate server: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>
[MAVENSMATE]: Could not load json response from mavensmate
[MAVENSMATE]: {'error': 'Request to the local MavensMate server failed. please ensure the MavensMate-app is running.'}
[MAVENSMATE] skipped community activity

**Comment by joeferraro** [comment]
Do you have mavensmate-app installed and is it running? https://github.com/joeferraro/MavensMate-app

**Comment by Inbarajd** [comment]
Its working now after installing MavensMate-App. So When ever I use Sublime text MavensMate-app should be up and running every time?

**Comment by joeferraro** [comment]
yes, you can set it to start automatically by setting `mm_start_mavensmate_app` to `true` in Sublime Text and ensuring `mm_mavensmate_app_location` is valid.
