### ISSUE TITLE
MavensMateApp: Project Clean does not respect package.xml

### ISSUE THREAD

**Issue by coolbulevar** [joeferraro/MavensMate-app#38]
Hi there.
Steps to reproduce.

1. Create new project with default metadata subscription.
2. Update src/package.xml by hand or grab it from a repo.
3. Select MavensMate -> Project Clean

Expected behavior and it was earlier: a project refreshed from server with regard to package.xml.
Actual result: 
- the project and **package.xml** updated based on MavensMateApp Metadata Subscription List.
- new sublime window opened with the same project

Windows 7 x64, SublimeText 3, v.0.0.7-beta4

**Comment by joeferraro** [comment]
OK, this is an interesting one. The workaround should be to update your project's subscription to include whichever types are included in your new package.xml. I have to think about whether we should watch the package.xml and derive the subscription as it's updated.

**Comment by coolbulevar** [comment]
Seems the issue was fixed with v0.0.10 update on Win7 x64.
Great job Joe!
