### ISSUE TITLE
 "Error: Request Entity Too Large: head" when Irun Unit test using MavensMate-app

### ISSUE THREAD

**Issue by AkramGargouri** [joeferraro/MavensMate-app#39]
![image](https://cloud.githubusercontent.com/assets/1950254/10218816/faef26c0-6839-11e5-97fd-082f32798338.png)

**Comment by joeferraro** [comment]
How many Apex classes are in your project?

**Comment by AkramGargouri** [comment]
925 TestClass in total

**Comment by joeferraro** [comment]
thanks and what version of mm-app are you running?

**Comment by joeferraro** [comment]
this release reduces our testing payload chunk further in hopes of resolving this issue. please let me know if it resolves this: https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.9-beta2

**Comment by AkramGargouri** [comment]
@joeferraro it looks fine. thank you
