### ISSUE TITLE
Metadata Creation Page Required Fields

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/mavensmate-app#4]
When creating new metadata with the app, we should require fields that are needed for metadata creation.

For example, I can create a new vf page, but not specify the name of the page, which eventually leads to a nasty error message.

**Comment by joeferraro** [comment]
please log at https://github.com/joeferraro/MavensMate

**Comment by ralphcallaway** [comment]
@joeferraro can you add a little clarification on where the line is between the mavensmate app and the mavensmate core? that'll help me post issues to the right repo ...

**Comment by ralphcallaway** [comment]
migrated to https://github.com/joeferraro/MavensMate/issues/488
