### ISSUE TITLE
deploy not working

### ISSUE THREAD

**Issue by KoenVM** [joeferraro/MavensMate-app#41]
Even though the correct credentials are supplied, the deploy functionality is not working.
I'm on the latest version of the MavensMate-app. (v0.0.7-beta4)
It's throwing an "INVALID_LOGIN: Invalid username, password, security token; or user locked out." every time. 

I also don't see these "invalid" logins coming in on my user in Salesforce in the login history.
I do see the succesfull login when adding the connection but afterwards, no failed ones..

EDIT: just had a look in the logs. It seems that even though "Sandbox" is chosen, it is trying to connect to login.salesforce.com .. Easy to fix I guess? - using change sets in the meantime

**Comment by KoenVM** [comment]
temporary workaround that seems to work is adding sandbox connections as "Custom URL" with https://test.salesforce.com .

**Comment by joeferraro** [comment]
OK, so this issue is specific to sandboxes then?

**Comment by KoenVM** [comment]
yep, indeed if you choose "Sandbox" as the connection type. Not sure if it's also there for other special org types like pre-release.

**Comment by joeferraro** [comment]
@KoenVM fix available in https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.7
