### ISSUE TITLE
Refresh file from Server throws Error

### ISSUE THREAD

**Issue by banderson5144** [joeferraro/MavensMate-app#43]
When I try to refresh a file from Salesforce, I receive this error:
![image](https://cloud.githubusercontent.com/assets/2395774/10224966/8515250e-682e-11e5-820e-5008cdbc5b3b.png)

**Comment by banderson5144** [comment]
Fixed it. PATH variable was messed up.

**Comment by joeferraro** [comment]
@banderson5144 thanks for the update. For clarity's sake if anyone else runs into this issue, MavensMate uses the `cscript` executable to run a `vbs` script (yeah, i know) to unzip files returned from the salesforce metadata api. if you run into this exception, you need to make sure you have `C:\system32` on your PATH so we can use it :+1:

**Comment by banderson5144** [comment]
Your stuff is written in Node right? How come you're not using [JSZip](https://stuk.github.io/jszip/)?

**Comment by joeferraro** [comment]
@banderson5144 believe me, we've tried every single node zip project, they all fall over with complicated zip archives.

**Comment by joeferraro** [comment]
@archita6 you mentioned you have cscript available in system32, but is your PATH configured properly?

**Comment by archita6** [comment]
@joeferraro  Thanks . Updating the path fixed my issue.

**Comment by joeferraro** [comment]
see this post if you do not have script host enabled on windows: https://github.com/joeferraro/MavensMate-Atom/issues/186#issuecomment-145087785
