### ISSUE TITLE
Can't reset Security Token

### ISSUE THREAD

**Issue by jimrae** [joeferraro/MavensMate-app#44]
I have an org that I had to reset the security token on. Now, when I try to select "Edit Project" from sublime, I get an error: 
Operation: Opening Edit Project dialog
Timestamp: Thu, 01 Oct 2015 11:19:21
   Result: [ERROR]: Request to the local MavensMate server failed. Error initializing project: LOGIN_MUST_USE_SECURITY_TOKEN: Invalid username, password, security token; or user locked out. Are you at a new location? When accessing Salesforce--either via a desktop client or the API--from outside of your company’s trusted networks, you must add a security token to your password to log in. To receive a new security token, log in to salesforce.com at http://login.salesforce.com and click Setup | My Personal Information | Reset Security Token.

I have the new token, I just can't figure out how to add it to the project.

**Comment by joeferraro** [comment]
this should be resolved here: https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.9-beta1
