### ISSUE TITLE
Question: Is there a way to create a MM project from an existing folder with version 5?

### ISSUE THREAD

**Issue by jimrae** [joeferraro/MavensMate-app#46]
Before the upgrade, I could pull down a github repo with a clone, and drag it into Sublime, and select "Create product from Existing directory".
Is this still possible in Version 5? That option doesn't exist.

**Comment by joeferraro** [comment]
Hi @jimrae, you don't see this when right clicking the root? What's the structure of the directory in question?

<img width="481" alt="screen shot 2015-10-01 at 1 52 59 pm" src="https://cloud.githubusercontent.com/assets/54157/10229004/cdc19f02-6843-11e5-818c-a4d389fa2908.png">

**Comment by jimrae** [comment]
Well I do now, I swear I looked before.  Sorry about that.------ Original Message ------From: Joe FerraroTo: joeferraro/MavensMate-appCc: Jim RaeSent: October 1, 2015 at 2:43 PMSubject: Re: [MavensMate-app] Question: Is there a way to create a MM project from an existing folder with version 5? (#46)Hi @jimrae, you don't see this when right clicking the root? What's the structure of the directory in question?

**Comment by joeferraro** [comment]
ha no worries
