### ISSUE TITLE
Unable to open project in MM UI if SharingOwnerRule or SharingOwnerRule are in package.xml

### ISSUE THREAD

**Issue by adelorme82** [joeferraro/MavensMate-app#47]
I was trying to open my project in the MM UI, but it could never get past the spinner - it would not open the project. I turned on the logging and the issue seems to be my SharingOwnerRule or SharingOwnerRule entries in package.xml, because when I remove those from package.xml the project opens with no issues.

I have attached what I believe are the relevant parts of my packge.xml, the .sharingRules files that I am referencing and what I think the issue is in the .describe file.

Please let me know if you need any more information

https://gist.github.com/adelorme82/f3d2f47e4112b3a5dce4

**Comment by joeferraro** [comment]
super helpful, thanks. looking into it

**Comment by joeferraro** [comment]
this release (https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.8) attempts to resolve your issue. feel free to re-open if you still encounter it. cheers for the logs.

**Comment by adelorme82** [comment]
That seemed to fix it, Joe! Thanks for the quick fix

**Comment by joeferraro** [comment]
@adelorme82 no problem, :+1:
