### ISSUE TITLE
Expose an API for editing the project credentials in CLI

### ISSUE THREAD

**Issue by ckoppelman** [joeferraro/MavensMate-app#48]
When I'm developing using Git, I like to correlate Git branches with Salesforce environments (sandboxes, dev orgs, production, whatever).  It's a pretty common use case.

When I change my branch, I always need to remember to change my MavensMate credentials.  I'd like to be able to correlate those somehow (and not commit my password to source control), so that when I switch branches, MavensMate automatically knows that I'm in, e.g., my `.staging` sandbox.  I would be happy to write up a `post-checkout` hook for this, but I have no idea what mm commands to call if those exist.  Any ideas?

**Comment by joeferraro** [comment]
you can use the mavensmate cli for this:

```
npm intall mavensmate -g
mavensmate update-creds <username> <password> <orgType> <loginUrl>
```

examples:

```
mavensmate update-creds foo@bar.com password1
mavensmate update-creds foo@bar.com password1 developer
mavensmate update-creds foo@bar.com password1 production
mavensmate update-creds foo@bar.com password1 sandbox
mavensmate update-creds foo@bar.com password1 custom https://mycustom.url.com
```

**Comment by ckoppelman** [comment]
Super! Thanks and sorry for not reading the docs.  I'll see if I can get up a gist of my githook when I can write it.
