### ISSUE TITLE
Easy, one-button refresh-all-from-server?

### ISSUE THREAD

**Issue by ericeslinger** [joeferraro/MavensMate-app#50]
I may be missing a subtlety in MM, but is there an easy way in either the overall app or in the atom plugin to just refresh an entire project from the server? I can refresh individual files via right-clicking in Atom, but there's no obvious button to use in the app.

My particular use case is: some people I work with edit their dev sandbox online using the salesforce web UI, but need to use MM (or something - eclipse is heavy-duty for this) to download the project source code into a directory that's *also* checked into a git repo. They'll similarly need to pull their git from an upstream (after a different dev merges a PR into the upstream master) and use MM to deploy from their local computer to their sandbox.

I wish there was just a native git integration with force, to have a sandbox just track a branch on a github repo, but this seems to be the next-best way. Right now, though, I have to know what files are out of date between my local computer and the remote server (with the server instance sometimes being fresher than the local computer's)

**Comment by joeferraro** [comment]
does the `clean project` command meet your needs? it resets your local project to its server state based on your package.xml

**Comment by ericeslinger** [comment]
Hmm, actually it looks like I just missed the process - if I'm in the MM
app and then open the project, and then hit "Edit Project", the big blue
"update project" button does what I need. I updated some files in my
sandbox, and it seems to have pulled those changes to my local machine.
