### ISSUE TITLE
Error creating new Project after MM 5.0 update

### ISSUE THREAD

**Issue by amitgithubuser** [joeferraro/MavensMate-app#52]
Not able to create new project after MM 5.0 update

I am using windows 7. I have Mavensmate app installed and I am trying to create new project.
Attached is the error received when creating new project.

![mavensmate-error-new-project](https://cloud.githubusercontent.com/assets/5687840/10232082/1b2e03ea-684c-11e5-94b8-f2b6a5b9494e.PNG)

**Comment by joeferraro** [comment]
please do not create duplicate issues, thanks https://github.com/joeferraro/MavensMate-SublimeText/issues/684
