### ISSUE TITLE
Windows x64 version installs in x86 directory

### ISSUE THREAD

**Issue by davidwoodytodd** [joeferraro/MavensMate-app#53]
Joe,
both versions of the Latest Release for Windows (MavensMate-app-v0.0.7-beta4-win-x64-setup.zip, MavensMate-app-v0.0.7-beta4-win-x86-setup.zip) install to the x86 directory. Also the global setting for the MavenMate App path points to the 64 bit directory by default, but since the install is not there, it fails.

**Comment by joeferraro** [comment]
@davidwoodytodd have a try with this one, https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.7 .. this gives the option to do a portable install as well. if you're satisfied, i can mark x64 off as validated for the build

**Comment by davidwoodytodd** [comment]
Joe, this seems to work ok. The only strange thing is that the installation didn't automatically create a start menu icon like the previous install. Not a huge issue of course.
Thanks Joe!

**Comment by joeferraro** [comment]
on top of it, will be available soon https://github.com/joeferraro/MavensMate-app/issues/51
