### ISSUE TITLE
Error Creating New Project/Refreshing existing project 

### ISSUE THREAD

**Issue by archita6** [joeferraro/MavensMate-app#54]
I am not able to create a project or refresh existing project after . I have updated the maven-app settings after installing the maven -app.  I tried installing multiple versions from the site https://github.com/joeferraro/mavensmate-app/releases
But will all versions I am getting the same error.  I have the Sublime text 3 as editor and have installed the Mavens Mate plugin to it
![image](https://cloud.githubusercontent.com/assets/6512067/10232421/897f6654-683d-11e5-9b55-cc63c1d45b72.png)

Following are my mavens mate settings in the maven-app
Workspaces (mm_workspace)
 Array of local workspaces. These should be absolute paths. 

Example:
*nix Example: [ "/path/to/workspace", "path/to/another/workspace" ]
Windows Example: [ "C:\\some\\path", "C:\\another\\path" ]

[
  "C:\\salesforce\\mavenWorkspace"
]
Salesforce API Version (mm_api_version)
 The API version you would like to use when accessing the Salesforce APIs.

Check conflicts before compile (mm_compile_check_conflicts)
 Set to true to check for conflicts when compiling Apex/Visualforce metadata.
Download categorized Apex unit test logs (mm_download_categorized_test_logs)
 Set to true to download Apex unit test logs to your project's debug/<test-name>/ directory
Timeout, in seconds (mm_timeout)
 Timeout (in seconds) for MavensMate commands.

Default metadata subscription (mm_default_subscription)
 Array of metadata types that should be included in every new MavensMate project, e.g. ApexClass, ApexPage, CustomObject, StaticResource

[
  "ApexClass",
  "ApexComponent",
  "ApexPage",
  "ApexTrigger",
  "StaticResource"
]
Ignore managed metadata (mm_ignore_managed_metadata)
 Set to true to prevent managed metadata from being downloaded to your MavensMate projects
Use keyring (mm_use_keyring)
 Set to true if you would like MavensMate to use your machine's keychain support to store/retrieve Salesforce.com credentials. If set to false, MavensMate will store passwords in plain text in your project's config/.settings and config/.org_connections files.
Compile Apex/Visualforce metadata with Tooling API (mm_compile_with_tooling_api)
 Set to true to use the tooling api to compile apex metadata (if you're experiencing compile issues, set this to false to use the metadata api)
Sublime Text location (mm_subl_location)
 The full path of your Sublime Text executable (Sublime Text users only).

{
  "windows": "C:\\Program Files\\Sublime Text 3\\sublime_text.exe",
  "linux": "/usr/bin/subl",
  "osx": "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl"
}
Atom executable location (mm_atom_exec_path)
 The full path to atom executable (Atom users only).

{
  "windows": "C:\\Program Files\\Atom\\Atom.exe",
  "linux": "/usr/bin/subl",
  "osx": "/usr/local/bin/atom"
}
MavensMate logs location (mm_log_location)
 Full path to the location where you would like MavensMate to store its logs. When this and mm_log_level are set, MavensMate will write logs to this path with the file name mavensmate.log. Relevant logs should be included with any bug reports.

Plugin log level (mm_log_level)
 Possible values: INFO, WARN, DEBUG, VERBOSE, SILLY

Play sounds (mm_play_sounds)
 Set to true if you would like MavensMate to play notification sounds on events like deployments, unit tests, etc.
MavensMate templates location (mm_template_location)
 Possible values: remote or local. Set to "remote" when templates should be sourced from GitHub. Set to "local" if you have cloned MavensMate-Templates locally and wish to source templates from your local file system.

MavensMate template source (mm_template_source)
 If "mm_template_location" is set to "local", set this to the absolute location of the directory where you've forked the MavensMate-Templates project. 

Example:
"/path/on/your/machine/to/templates"
If "mm_template_location" is set to "remote", set to github location ("username/reponame/branchname"). Project structure must be in the format found here: https://github.com/joeferraro/MavensMate-Templates

Salesforce file extensions (mm_apex_file_extensions)
 Array of file extensions that should be considered "Salesforce" file extensions.

[
  ".page",
  ".component",
  ".cls",
  ".object",
  ".trigger",
  ".layout",
  ".resource",
HTTP Proxy (mm_http_proxy)
 Set if you are behind a proxy (you can also set via export HTTP_PROXY, export HTTPS_PROXY). Example: http://10.10.1.10:3128 or http://user:pass@10.10.1.10:3128/

HTTPS Proxy (mm_https_proxy)
 Set if you are behind a proxy (you can also set via export HTTP_PROXY, export HTTPS_PROXY). Example: http://10.10.1.10:3128 or http://user:pass@10.10.1.10:3128/

MavensMate app path (mm_mavensmate_app_path)
 Full path to your MavensMate app

{
  "windows": "C:\\Program Files\\MavensMate\\mavensmate.exe",
  "linux": "/usr/bin/mavensmate-app/MavensMate",
  "osx": "/Applications/MavensMate.app"
}
Purge on delete (mm_purge_on_delete)
 Set to true to perform a hard delete when deleting metadata.
Use browser as UI (mm_use_browser_as_ui)
 Set to true to open MavensMate UIs in your default browser (advanced users only)

**Comment by joeferraro** [comment]
dup of https://github.com/joeferraro/MavensMate-app/issues/43
