### ISSUE TITLE
Class / Trigger coverage now available after debugging. v0.0.8

### ISSUE THREAD

**Issue by brandonpadula** [joeferraro/MavensMate-app#55]
After running tests in the new app (Mac), I'm unable to see class coverage or trigger coverage. I've tried on a coworker's computer (Mac) and it works fine, so I'm not sure what has changed. 

Before this update, however, it did work on my machine. 

Any help would be greatly appreciated!
Brandon

**Comment by joeferraro** [comment]
Hi, need a bit more info. You don't see these options after running tests?

<img width="313" alt="mavensmate" src="https://cloud.githubusercontent.com/assets/54157/10247190/5427da24-68e5-11e5-967e-6f778ec7ec64.png">

**Comment by brandonpadula** [comment]
Hi,
I have those options, but there isn't anything inside it. See attached. (I get the same blank screen in class coverage as well)

<img width="1085" alt="screen shot 2015-10-02 at 10 09 05 am" src="https://cloud.githubusercontent.com/assets/14940893/10248470/ad157404-68ed-11e5-84f2-52efa1e364f1.png">
<img width="405" alt="screen shot 2015-10-02 at 10 08 41 am" src="https://cloud.githubusercontent.com/assets/14940893/10248469/ad12f2f6-68ed-11e5-904a-e1c7e86a41ac.png">
<img width="399" alt="screen shot 2015-10-02 at 10 08 22 am" src="https://cloud.githubusercontent.com/assets/14940893/10248471/ad16b2a6-68ed-11e5-9a57-366c86bb02f4.png">

**Comment by joeferraro** [comment]
OK, and how many non-test classes/triggers are in your project?

**Comment by brandonpadula** [comment]
There's 8 Non-Test classes and 3 Triggers

I actually just tried it on another project and it worked, but I'm getting an error on this one now that says "invalid project metadata cache". I refreshed the index via sublime as well as in the mavens mate app. Any idea why I'm still getting an error?

**Comment by joeferraro** [comment]
Hi @brandonpadula is this a new project you created after v5? If not, can I suggest attempting to re-create the project and see whether the issue persists?

**Comment by brandonpadula** [comment]
Hi Joe,
Looks like that made it work!

Brandon
