### ISSUE TITLE
Can not get debug logs from apex unit test run

### ISSUE THREAD

**Issue by amitgithubuser** [joeferraro/MavensMate-app#58]
using mavensmate app on windows 7.

1. mm_log_level is set under settings in the app
2. mm_log_location is set under setting in the app
3. I click on "Start Logging"
4. I run unit test
5. test run is successful
6. Can't fine any logs under log directory
7. no way to get/see logs

pls help how to do this and how to use mavensmate app.
Is there a way I can roll back to what I had and don't deal with the app until it is stable.

**Comment by kirk-clawson** [comment]
That setting is for the MavensMate-app log, not your Apex logs. Your Apex logs can be found in [Workspace]/[Project]/debug/logs.

If you still feel the need to rollback to previous version see here : https://github.com/joeferraro/MavensMate-SublimeText#install

(Assuming you're in Sublime)

**Comment by joeferraro** [comment]
indeed, `mm_log_level` and `mm_log_location` are for MavensMate logs. To gather your Salesforce logs, simply run the start logging command and run your test. Logs will be streamed to your project's debug/logs directory.

**Comment by lifewithryan** [comment]
I know this is closed but my project doesn't seem to have a "debug" folder anywhere. Do I need to create this?

**Comment by lifewithryan** [comment]
nevermind, I got it going now

**Comment by oski1993** [comment]
@lifewithryan - what did you do to get it going? i'm also not able to get the "debug" folder created even after doing a 'Start Logging'... thx.

**Comment by lifewithryan** [comment]
@oski1993 I think, (it's been awhile), that I just created the directories manually and that got it all going. Take this with a grain of salt however because that was nearly a year ago :)

**Comment by vijay24805** [comment]
I don't see a project debug folder. I click start logging and executed an anonymous apex code but no folders created.

**Comment by ohaucke** [comment]
> Update: August 7, 2017
> MavensMate is no longer being actively developed or supported.

**Comment by e02d96ec16** [comment]
@vijay24805 Try with your MM settings set to API version 34.0. Any later won't work I think.
