### ISSUE TITLE
SharingRule now breaks package.xml

### ISSUE THREAD

**Issue by ckoppelman** [joeferraro/MavensMate-app#59]
The fix to #47 seems to have broken package.xml when SharingRule is included.

**Comment by joeferraro** [comment]
Can you post a breaking package.xml? thanks

**Comment by ckoppelman** [comment]
When I remove these lines from package.xml, it works without issue:

    <types>
        <members>*</members>
        <name>SharingRule</name>
    </types>

Is it possible to do no verification on package.xml?  The specs change much too suddenly for a thrid-party project to keep up with.

**Comment by joeferraro** [comment]
What version of the API? I was under the impression that it was:

```
<types>
    <members>*</members>
    <name>SharingRules</name>
</types>
```

http://docs.releasenotes.salesforce.com/en-us/spring15/release-notes/rn_api_meta.htm

**Comment by ckoppelman** [comment]
Yes.  The following works using the Ant tool:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
		<members>*</members>
    	<name>SharingRules</name>
	</types>
    <version>34.0</version>
</Package>
 ```

**Comment by joeferraro** [comment]
right, note the "s" on the end. Your previous package contained "SharingRule"

**Comment by ckoppelman** [comment]
I see.  You are correct.  Even so, I feel like there needs to be less validation from MavensMate-app.
