### ISSUE TITLE
Editor doesn't open new metadata after creation

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/mavensmate-app#6]
When a new piece of metadata is created with the new app, it no longer opens the file in the text editor

**Comment by joeferraro** [comment]
can you log these at https://github.com/joeferraro/MavensMate? This project is only for the wrapper around MavensMate. I realize it can be difficult to tell the difference, but assume non-editor related issues go to the main MavensMate project

**Comment by ralphcallaway** [comment]
@joeferraro will do, i'll shift these over tomorrow morning ...

**Comment by ralphcallaway** [comment]
migrated to https://github.com/joeferraro/MavensMate-SublimeText/issues/630
