### ISSUE TITLE
Cannot Deploy Resource Bundle

### ISSUE THREAD

**Issue by skwilder** [joeferraro/MavensMate-app#60]
After upgrading to Mavensmate v0.0.8 I cannot Deploy Resource Bundles anymore. I have attempted to delete the resource folder, refresh my .resource file in src/staticresources/ from the server and re-create the resource bundle through the Create Resource Bundle Interface.

After re-creating the change set I attempting to upload the resource to Salesforce user Deploy Resource Bundle the Mavensmate app throws an error. I have included that screenshot in this post.

![screen shot 2015-10-02 at 3 21 25 pm](https://cloud.githubusercontent.com/assets/1234082/10255574/48b0f016-6919-11e5-98f3-b285d7a255da.png)

The file mentioned in the screenshot did exist but it was deleted as part of the error.

**Comment by joeferraro** [comment]
Can you paste your mm_workspace setting from mavensmate-app?

**Comment by skwilder** [comment]
[
  "Users/shawnwilder/Documents/Projects/mm_workspace"
]

**Comment by joeferraro** [comment]
please update to:

[
  "/Users/shawnwilder/Documents/Projects/mm_workspace"
]

"Users/shawnwilder/Documents/Projects/mm_workspace" is not a valid path. We will be releasing an update to the settings module that will throw an error if/when you add an invalid path.

**Comment by skwilder** [comment]
Thanks that worked. The flavour text above it lends to believe that it would be either way.

**Comment by joeferraro** [comment]
you're right, that's a typo, thanks!
