### ISSUE TITLE
>120 sec save time for classes

### ISSUE THREAD

**Issue by NWilliamsSCU** [joeferraro/MavensMate-app#61]
Saving is so painful I'm forced to abandon MavensMate even though it has been a godsend to me.  I have set mm_compile_with_tooling_api to true and it doesn't make a difference.  I've also tried backdating the API to version 33.0 since that had been what I was still working on prior to MavensMate-app and no dice.  I also tried to see how long it would take to save in salesforce's interface and it's very quick (so not an issue on their side that I can see).

I am running:
- Sublime 3 (build 3083)
- Sublime Package Control
- MavensMate.app v0.0.8 (latest)

**Comment by joeferraro** [comment]
dup of https://github.com/joeferraro/MavensMate-SublimeText/issues/686

you're welcome to go back to v4, but based on the comments in the above issue, this is a salesforce server issue: https://github.com/joeferraro/MavensMate-SublimeText#version-4-no-longer-supported
