### ISSUE TITLE
Project .settings file variable name change

### ISSUE THREAD

**Issue by techman97** [joeferraro/MavensMate-app#62]
In the previous version of MM, the "Project Name" node in the .settings JSON file was "project_name".  In v5, it's now "projectName".

**Comment by joeferraro** [comment]
indeed. have you seen any consequences of this change in v5?

**Comment by techman97** [comment]
No idea - have been changing it in the process of migrating my projects to the new version.  Don't know what back-end stuff that supports?  If it's just a random value, close this out.  =)

**Comment by joeferraro** [comment]
ha, it certainly was not random; it was an intentional change to conform to JavaScript [camelcase] conventions. if you run into any problems as a result of this change, feel free to re-open. cheers, Andy.

**Comment by joeferraro** [comment]
oh and by the way, in the next release of mm-app, running "clean project" should basically fix anything you may have encountered in a "legacy" project

**Comment by techman97** [comment]
Awesome!

If you're doing that - also unless I put a "password" node in the settings
JSON, I can't open the project via mm-app.  Grab that if you're doing a
clean.  =)

**Comment by joeferraro** [comment]
Right, that's because you're not using keyring/keychain. Not much we can do about that, because we don't know your password :)
