### ISSUE TITLE
Error message incorrect in Atom when missing local server

### ISSUE THREAD

**Issue by ianzepp** [joeferraro/MavensMate-app#63]
Installed the beta package for Atom. Received the following error:

<img width="1125" alt="screen shot 2015-10-03 at 12 29 14 pm" src="https://cloud.githubusercontent.com/assets/757705/10263869/9e5ef614-69ca-11e5-9330-c8e580c0d738.png">

Trying to go to the URL there results in a Github 404 error, as the github repository is misspelled. Should be:

https://github.com/joeferraro/MavensMate-app/

**Comment by joeferraro** [comment]
thanks this is merely a typo that's been fixed in 1.0.6. cheers

https://github.com/joeferraro/MavensMate-Atom/commit/b83983b4fb862fe49110d11caeccf5b3f0f6c724
