### ISSUE TITLE
New Project is empty after creating

### ISSUE THREAD

**Issue by amitgithubuser** [joeferraro/MavensMate-app#68]
installed - 
Mavensmate app v0.0.9 on Windows 7

below are the steps

1. Created New project
2. selected additional metadata components
3.  New project creation is successful but there are no metadata components in the created project on the disk.
4. "Project Metadata" tab in the mavensmate app shows everything unselected and when expanded any option, everything is empty

pls see attached screenshot
![mavensmate-error-create-new-project](https://cloud.githubusercontent.com/assets/5687840/10289775/d0d6b14e-6b65-11e5-8b11-0813b00c8e50.PNG)

**Comment by joeferraro** [comment]
The order of operations to create a new project:

1. enter your credentials
2. click the project metadata to select the metadata components you wish to be part of your project
3. click "create project"

you can close the mm-app tab after you've done that. to modify what's in your project, run the edit project command.

does that make sense?

**Comment by joeferraro** [comment]
closing for now. if you're still experiencing this issue, please re-open with logs pasted to the issue to assist in debugging. thanks!
