### ISSUE TITLE
Custom Mavensmate template location is not identified

### ISSUE THREAD

**Issue by VineelaKos** [joeferraro/MavensMate-app#69]
Hello,

I have installed the mavensmate templates from the github and customized the template. With the new version 5of Mavensmate for Sublime, I have updated global settings to use the local instead of remote path  and specified the local path to the mavensmate templates folder. I am using a windows OS and so have the below format to specif the path:

C:\\user\VK\MavensMate-templates

When I create a new apex class , the customized template is not being used instead the default template from remote location is used.

Please let me know if this is a bug or I am missing something?

Thanks!
Vineela

**Comment by VineelaKos** [comment]
Hello,

I am using Mavensmate for Sublime text. I am not sure how to upgrade the mavensmate to this package. Could you please share the directions for this upgrade. 

Also, could you please let me know the location format that has to be specified in the Mavensmate global settings. I am currently using the below format.

C:\Users\VK\MavensMate-Templates

Appreciate your help with this!

**Comment by joeferraro** [comment]
this fix is available in https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.10-beta1

**Comment by VineelaKos** [comment]
Hi Joe,

Thanks for sharing this link to upgrade. This time, the custom template was displayed during creation in MavensMate-app but when the class opened in Sublime it had the original template from remote. 
Could you please let me know if there is any other configuration that I have to do.

Thanks for your help!

**Comment by joeferraro** [comment]
hm, let me have a look to see what's going on @VineelaKos

**Comment by VineelaKos** [comment]
Sure, thank you Joe

**Comment by VineelaKos** [comment]
Hi @joeferraro ,

Could you let me know if you have any update on this.

Thank you

**Comment by joeferraro** [comment]
fix should be in https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.10-beta3, but still validating

**Comment by VineelaKos** [comment]
Thanks @joeferraro . I just tested and it worked for me!

**Comment by joeferraro** [comment]
cheers @VineelaKos
