### ISSUE TITLE
Don't Close App when Window Closed

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/mavensmate-app#7]
Currently if the mavensmate app window is closed the program exits, and mm functionality ceases to work in the related editor. Since the mm app window is in theory just to support the plugin, it would be helpful to be able to close the app window without quitting the underlying application.

**Comment by joeferraro** [comment]
TODO: when final window closes, keep app open. on open request from core, detect no windows open, pop new window and add necessary tab
