### ISSUE TITLE
Loading spinner causing 100% CPU usage

### ISSUE THREAD

**Issue by jdcrensh** [joeferraro/MavensMate-app#73]
Only started happening after updating to v0.0.9, and happens only when deploying to another org. CPU returns to normal when it completes...

Running on OSX El Capitan and ST3

mm_api_version: '33.0'
mm_compile_with_tooling_api: true

**Comment by jdcrensh** [comment]
Only started happening after updating to v0.0.9, and happens only when deploying to another org. CPU returns to normal when it completes...

Running on OSX El Capitan and ST3

**Comment by pchittum** [comment]
Are you using the Lightning Sublime plugin, by chance? Since upgrading, I've found that having both plugins enabled in Sublime Text results in force-cli exhibiting very high CPU (near 100%). Force-cli is the underlying engine for Sublime Lightning. I've had "interesting" interactions between these two plugins before. So far, disabling Sublime Lightning seems to be keeping things in check.

**Comment by jdcrensh** [comment]
I don't have that plugin installed, so it can't be the issue... It's a minor annoyance when I'm deploying to have my machine lag a little bit. I've worked around it by closing the window after starting the deploy and monitoring it through the Salesforce UI.

**Comment by viraj89** [comment]
I had few sought of similar issues running on v0.0.9. I upgraded it to v0.0.10. 
v0.0.10 is as far the stable release I've being experiencing, especially with the UI/UX & syncing issues. 
Get the v0.0.10 - https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.10
Also suggest you to install the latest plugin of sublime text 3 - https://github.com/joeferraro/MavensMate-SublimeText

**Comment by jdcrensh** [comment]
I've been using v0.0.10 of the app for weeks now, and the issue is still there. It's unrelated to the ST3 plugin. The usage is coming from the app's Electron Framework process...

OS X El Capitan, if that helps any.

**Comment by jdcrensh** [comment]
This is still an issue in v0.0.11.

I noticed that the CPU spikes every time the spinner appears. Could be a repainting issue?

https://discuss.atom.io/t/atomhelper-high-cpu-usage/2553/83

**Comment by joeferraro** [comment]
@jdcrensh super interesting. will take a look

**Comment by jdcrensh** [comment]
Verified by removing the animated elements in [loading.html](https://github.com/joeferraro/MavensMate-app/blob/master/app/loading.html) and [layouts/base.html](https://github.com/joeferraro/MavensMate/blob/master/lib/mavensmate/ui/templates/layouts/base.html#L293). Node's CPU usage dropped from ~100% to 5-20% while updating a project's metadata.

I attempted to force hardware acceleration with `transform: translateZ(0)` as some blogs suggested. This _seemed_ to help with the system lag, but the node process still reported as running at at ~100%.
