### ISSUE TITLE
BLOCKING ISSUE - MavensMate file not found (Since this morning)

### ISSUE THREAD

**Issue by ylhutter** [joeferraro/MavensMate-app#74]
![image](https://cloud.githubusercontent.com/assets/7148246/10332211/801aa1fe-6ce4-11e5-82fc-258df58bb671.png)

This morning got this message after opening Mavensmate v0.0.6 & v0.0.10 Beta 1 on Sublime text 3. This is a blocking issue (cannot refresh project or save). when I save I get this error:

![image](https://cloud.githubusercontent.com/assets/7148246/10332259/bf9cf8c2-6ce4-11e5-9fc4-b2346d33d778.png)

but my mm_workspace has been already defined properly:
![image](https://cloud.githubusercontent.com/assets/7148246/10332553/ad60cb64-6ce6-11e5-9ad0-019af3327d9e.png)

Please assist it is reflecting on more developers as I noticed.

**Comment by ylhutter** [comment]
I managed to solve it myself:

press the windows button + shift + , then mavensmate settings will open. note that you don't have mm_workspace attribute. add this line:

mm_workspace" : "C:\\your_workspace_path",

And ctrl + s

**Comment by DarrinDipity** [comment]
I had the same problem, but I thought the purpose of the mavensmate app (and making the setting there) was that I would not have to do the same in Sublime under the MavensMate > Settings > User dialog.

**Comment by joeferraro** [comment]
Hi guys, apologies the confusion, but v6 (previously v4.0.5) has no concept of MavensMate-app (this is v7 only), therefore, settings need to be managed within Sublime Text as @DarrinDipity and @ylhutter describe.
