### ISSUE TITLE
Delete of Class(s) in Production

### ISSUE THREAD

**Issue by DavidACL** [joeferraro/MavensMate-app#77]
I've been attempting to find a non-ANT solution for deleting classes in a Production org:

I have found a solution for individual classes by:
1.  Turning off the Tooling API in MavensMate-App setup (seems to be required)
2.  Editing the class's meta-xml file (status = Active -> status = Deleted)

This triggers a full unit test run, and works.  Previously, I believe 'right-click-on-class->delete from server' worked in a project linked to a Production instance (still with a fill test run).  

My issue is finding a MavensMate way of deleting multiple files simultaneously (single unit test run).  Previously, I believe that in previous MavensMate versions I was able to alt-click multipul files in Sublime file tree then  'right-click->delete from server'.  Now I get "INVALID_OPERATION: purgeOnDelete option can only be used on a non-active org"

Editing multiple meta-xml files and trying file->save-all just queues them one at a time (multipule full test runs.  

If I understand the community's findings, only Ant Migration tool has this capability through destructiveChanges.xml (it seems Eclipse could not do this).

I wanted to validate that this multi-delete was in fact not possible in previous versions of MavensMate (contrary to my memory) and if not, request that it is considered in the future.  

Thanks!!

**Comment by joeferraro** [comment]
You can toggle `mm_purge_on_delete` to `false` in your mm-app's settings, then try your deletion again.
