### ISSUE TITLE
Suddenly getting [OPERATION FAILED] Error

### ISSUE THREAD

**Issue by dannyshox** [joeferraro/MavensMate-app#79]
New update was working fine until I started getting this error today:

[OPERATION FAILED]: Please ensure mm_workspace is set to existing location(s) on your local drive

The setup is fine, I've double checked the paths (which were working) and they're fine too.

Any ideas?

Thanks.

**Comment by OrnIngvar** [comment]
A colleague had this issue yesterday. The solution was to check the settings in the mavensmate settings within sublime and not in the mavensmate-app since you probably got rolled back to version 6.

**Comment by dannyshox** [comment]
Ya that did the trick, thanks.
