### ISSUE TITLE
Defect - "Open in Sublime" button open multiple instances when there are multiple displays

### ISSUE THREAD

**Issue by gnanadeeptu** [joeferraro/MavensMate-app#83]
Hi Joe,

Sublime ends up opening two instances, when I have multiple displays connected to my machine.

Connected Displays = Instances Opened.

**Comment by gnanadeeptu** [comment]
While Atom is still good and works fine, not sure if this is to do with the native apps or mavens mate. please check.

**Comment by joeferraro** [comment]
thanks! dup of https://github.com/joeferraro/MavensMate/issues/572

**Comment by gnanadeeptu** [comment]
Ooopps!! Apologies.

**Comment by joeferraro** [comment]
no worries, @gnanadeeptu

**Comment by gnanadeeptu** [comment]
On a side note, on Atom Package seems to be failing to update. Do you know if I need to do anything specific.

**Comment by gnanadeeptu** [comment]
Fetching outdated packages and themes failed.Hide output…
Request for package information failed: <!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>

**Comment by gnanadeeptu** [comment]
![screen shot 2015-10-08 at 4 40 16 pm](https://cloud.githubusercontent.com/assets/1222452/10382678/4f349ffc-6ddb-11e5-9213-e8ec97163bdd.png)
