### ISSUE TITLE
Even with update, the app keeps telling me to update to the version I just updated

### ISSUE THREAD

**Issue by pjcarly** [joeferraro/MavensMate-app#84]
Hi,

First of all, thanks for the awesome work, we're a big fan!

For a few days, the application says:
> A new version of MavensMate (v0.0.9) is available for download (current: v0.0.7-beta4)

Even though I downloaded and installed the v0.0.9 a few times already.

My specs:
Windows 10
MavensMate 64bit

**Comment by joeferraro** [comment]
What version is listed in your help menu? 

<img width="242" alt="windows_10_x64" src="https://cloud.githubusercontent.com/assets/54157/10441465/0c73fcf0-7117-11e5-90b0-a184fca34a6d.png">

**Comment by pjcarly** [comment]
Hi Joe,

v0.0.9 is listed. So I guess everything is ok.
