### ISSUE TITLE
github EPERM: operation not permitted, rename unpackaged to src

### ISSUE THREAD

**Issue by deckblad** [joeferraro/MavensMate-app#87]
I'm getting this error when updating my local metadata. I can go to the workplace project dir and manually change the directory name, though.

Permissions on /src folder are full access for my user. 

Odd that MM-App can rename /src to /unpackaged (or delete src and create unpackaged?) but not rename /unpackaged back to /src

Any hints on what I may be doing wrong?

**Comment by joeferraro** [comment]
@deckblad you're windows, right? There are some super pesky PERM-related issues with node on windows. this update changes the way we do cleans/refreshes/edits of the src directory. let me know if it works for you: https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.10-beta4

**Comment by banderson5144** [comment]
@joeferraro do we have to uninstall or can we just install over top?

**Comment by joeferraro** [comment]
you can install over the top

**Comment by joeferraro** [comment]
@deckblad @banderson5144 if you guys could update me on whether 0.0.10-beta4 resolves your issue, that'd be super helpful. thanks!

**Comment by banderson5144** [comment]
@joeferraro seems to be working now. I had Atom.io open, created a new static resource and Apex Class through the SF UI, clicked on Edit project from MM App, then hit the update button and no errors. So far so good.

**Comment by joeferraro** [comment]
@deckblad how about you?

**Comment by deckblad** [comment]
Looks like it's working now, yes. I'm on 10 beta 5

**Comment by joeferraro** [comment]
cheers @deckblad

**Comment by anjlichhatwani** [comment]
Hi, 
I am new to Mavensmate. I am trying to create a new project.It gives me the following error. Also I am using the admin account.

EPERM: operation not permitted, mkdir 'c:\Users\anjli\workspaceSF\SIB'
