### ISSUE TITLE
“MavensMate” is damaged and can’t be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by mkdjns** [joeferraro/MavensMate-app#94]
<img width="428" alt="screen shot 2015-10-19 at 5 34 55 pm" src="https://cloud.githubusercontent.com/assets/884516/10595003/e4f0ef1e-7687-11e5-890e-a9d9112280a5.png">
Downloaded v0.0.10 and extracted the dmg. Copied mavensMate.app to my Applications folder, launched it, and got an "“MavensMate” is damaged and can’t be opened. You should move it to the Trash." error from OS X.

This is on OS X El Capitan.

**Comment by joeferraro** [comment]
This sounds like it could be a codesign/Gatekeeper issue. MavensMate.app has been signed for a few releases now, but it may be that I need to sign at a more granular level (specific libs/frameworks). I've updated the codesigning process during OSX builds in the 0.0.11-beta1 release. Would you mind letting me know whether it installs and runs for you? https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.11-beta1

Also, would you mind letting me know what the value of your "Allow applications downloaded from" configuration in Security & Privacy is set as?

![gatekeeper_identified_developers_-_google_search](https://cloud.githubusercontent.com/assets/54157/10596964/22558dda-76b8-11e5-84d2-c9c75f3402cf.png)

**Comment by mkdjns** [comment]
"Allow applications downloaded from" is set to "Mac App Store and identified developers".

Downloaded the 0.0.11-beta1 build and got the same message. As a further test, I downloaded the 0.0.9 release and had the same issue, even though I had been running that release previously.

Downloaded 0.0.10 once again using Safari instead of Chrome and all seems to be OK. Seems the issue was on my end. Sorry!

**Comment by joeferraro** [comment]
No worries. @mkdjns cheers for the follow-up

**Comment by NWilliamsSCU** [comment]
I'm still getting the same error even when I try using safari instead of Chrome.  I am also set to "Mac App Store and identified developers".  I tried completely removing from my PC including an "Empty Recycle Bin" and tried again with the 0.0.10 via Safari and no luck...  Anything else you did differently @mkdjns ?

**Comment by joeferraro** [comment]
here's some additional information re: this error: http://apple.stackexchange.com/questions/58050/damaged-and-cant-be-open-app-error-message

**Comment by NWilliamsSCU** [comment]
Genius!  Didn't realize it was a Mac-specific issue!  This is such a fantastic piece of software, I was panicking without it!

**Comment by joeferraro** [comment]
@NWilliamsSCU curious, what did you do to resolve this issue?

**Comment by NWilliamsSCU** [comment]
In Terminal, I ran:

$ xattr -rc /Applications/MavensMate.app

... fired right up after that...

**Comment by atnmorrison** [comment]
I'm getting this error and the suggestion to run xattr command didn't work

**Comment by joeferraro** [comment]
@atnmorrison what version?
