### ISSUE TITLE
auto-compile setting available?

### ISSUE THREAD

**Issue by seanhharrison** [joeferraro/MavensMate-app#96]
Yosemite 10.5.5
64-bit Intel Core i5
Sublime build 3083
MM v7.0.0-beta.1
MM-app v0.0.10-beta6
no firewall

Just curious if the auto-compile-on-save is still an option. I don't see it in the new Settings panel. I'd like to toggle it to "false" :-)

**Comment by joeferraro** [comment]
"mm_compile_on_save" in the sublime text user settings 

<img width="667" alt="screen shot 2015-10-20 at 5 53 09 pm" src="https://cloud.githubusercontent.com/assets/54157/10622142/78e757be-7753-11e5-9fdd-15204bd842bd.png">

**Comment by seanhharrison** [comment]
handled by the plug-in settings I see. Excellent, Thx, Joe
